### ISSUE TITLE
Is ok when integrating scRNA-seq dataset from Hippocampal region and ST dataset from mouse brain？

### ISSUE THREAD

**Issue by jiawei-zhong** [almaan/stereoscope#14]
Hi Alma,

I observed that scRNA-seq dataset is stemed from Hippocampal region while the ST dataset  is stemed from the whole mouse brain. Is ok that there two dataset are from different region? It will be better when change Hippocampal region scRNA-seq dataset to whole brain region？

Best regards,
Jiawei

**Comment by almaan** [comment]
Hello @jiawei-zhong ,

Well spotted! My answers to questions regarding how to choose single cell and spatial data sets are more or less always the same:  _the more similar they are, the better_. Preferably you want the cell type population in both data types to overlap as much as possible, it makes the estimation problem easier to solve. 

However this does not mean that the data needs to be perfectly matched in order for `stereoscope` to give factual results, as long as the single cell data is to some extent representative of the spatial data (w.r.t. to cell types). 

Whether the result will be "better" depends on the objective; of course if there are types present in the whole brain single cell data but lacking in the hippocampal data, these will not be mapped if using the latter (since they are not included in the data). Still, the cell types in the hippocampal scRNA-seq data, should be properly mapped down despite us using the whole section (as you may see some types mainly locate to the hippocamal region). 

Hope that answers your question
Alma

**Comment by jiawei-zhong** [comment]
Hi Alma,

Thanks a lot. I observed that the result of Neuron28 and Neuron60 in Supplementary Figure 12: these two cell types are not located in Hippocampal region but the cerebral cortex. However these two cell type are stemed from scRNA-seq data so it should be present in Hippocampal region.

I think may be Neuron28 and Neuron60 are both located in Hippocampal region and cerebral cortex but these are mainly located in cerebral cortex so the red dot are located in cerebral cortex. Does the high proportion of cell type in cerebral cortex(like Neuron28 and Neuron60) affect the visualization in Hippocampal region?

And did you ever tried to input whole brain scRNA-seq data, I found a dataset maybe suitable to fitly match the ST data. https://www.nature.com/articles/nn.4216#MOESM71

Best regards,
Jiawei

**Comment by almaan** [comment]
Hi Jiawei!

I see that you have really worked through the results very thoroughly, and made some sharp observations, thanks a lot for sharing those.

You are bringing the attention to a very important point when it comes to visualization of the results, and I believe your guess is very correct here. If there are very strong signals in one part of the tissue, these might "quench" weaker signals during the visualization - which you exemplify very neatly with the discussion regarding the certain Neuron cell types and their location in the cerebral cortex and hippocampal region respectively. There are two ways one could potentially work around this issue:

1. "Cap" your values - by setting all values larger than a certain threshold to the threshold value (e.g., the 99th percentile of your data values) the visualization becomes more robust to outliers. This however introduces the risk of misrepresenting the data.
2. Isolate the region of interest - subset the results to only include spots residing within the region of interest, e.g., hippocampus

I have not tried specifically to map such a single cell data set onto these slides, for the publication (it is in press) we deemed the set used sufficient to demonstrate the use of the method. However, I really appreciate you sharing your findings!

We did look at the single cell data you linked, but after assessing its GEO repo. - none of the files contained raw (whole integer) data from what I could see. Meaning it - the data - had been normalized in some regards and not really compatible with the `stereoscope` model (Negative Binomial).

Thanks again!
Alma
