### ISSUE TITLE
Plotting `stereoscope` results

### ISSUE THREAD

**Issue by cartal** [almaan/stereoscope#3]
Hi @almaan 

I'm having really promising results with `stereoscope`. Thanks for the help with the previous issue. 

I'm not trying to plot the results from my experiments and they are good, but I'm having a couple of issues:

1) I can't change the resolution of the plot or the palette (blue doesn't work well with my data). 

2) The joint plot comes up empty for me. 

Any advice on this? 

Thanks

**Comment by almaan** [comment]
Hi @cartal I'm excited to hear that!

Thank you for reporting these issues, I've pushed some updates which should help you.

1. There are now 2 additional arguments which you may provide to the `look` module. The first one is `--colormap CMAP` where CMAP is the name of a matplotlib colormap (for example: Blues, magma, PuRd). To exemplify, `--colormap PuRd` would give you a white-pinkish plot. You can find a list of all available of colormaps here : [LINK](https://matplotlib.org/tutorials/colors/colormaps.html). The second argument is `--side_size SIZE` which sets the subplot size (and thus implicitly increases the resolution) to SIZE pixels. The default size, which is what you've used up until now is 350, just to give you a reference. 

2. This issue should now be resolved if you include the flag `--hexagonal` when using `stereoscope look`. I've not added the interpolation feature, but will try to in a later update. 

Hope this helps, as usual, let me know otherwise!

**Comment by almaan** [comment]
After off-site discussion, updates seem to have resolved the issues. Thus I'm closing this.
